Repository Autonomy-Logic/openplc-editor, pull requests merged in 2024-03, with the labels that each got.

#57 FIX - Refactor the scroll areas at start screen
  src/renderer/features/screens/start/components/actions-bar/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/carousel-container.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/carousel-viewport.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/carousel.spec.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/index.ts
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/types.ts
  src/renderer/features/screens/start/components/display-example-projects/elements/header/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/index.ts
  src/renderer/features/screens/start/components/display-example-projects/elements/navigation/next-nav-button.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/navigation/prev-nav-button.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/wrapper/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/example-projects.spec.tsx
  src/renderer/features/screens/start/components/display-example-projects/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/types.ts
  src/renderer/features/screens/start/components/display-recent-projects/display-recent-project.spec.tsx
  src/renderer/features/screens/start/components/display-recent-projects/elements/display-recent-elements.spec.tsx
  src/renderer/features/screens/start/components/display-recent-projects/elements/header/index.tsx
  src/renderer/features/screens/start/components/display-recent-projects/elements/index.ts
  src/renderer/features/screens/start/components/display-recent-projects/elements/wrapper/index.tsx
  src/renderer/features/screens/start/components/display-recent-projects/index.tsx
  src/renderer/features/screens/start/components/display-recent-projects/types.ts
  src/renderer/styles/globals.css
Labels: bug

#58 Fix - Refactor titlebar
  package-lock.json
  src/main/main.ts
  src/renderer/features/layout.tsx
  src/renderer/features/screens/start/components/actions-bar/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/index.tsx
  src/renderer/index.ejs
  src/renderer/styles/globals.css
Labels: bug

#61 Fix - Refactor activity bar
  package-lock.json
  package.json
  src/locales/en/menu.json
  src/renderer/assets/icons/Types/iconTypes.tsx
  src/renderer/assets/icons/index.ts
  src/renderer/assets/icons/interface/ArrowUp.tsx
  src/renderer/assets/icons/interface/CodeIcon.tsx
  src/renderer/assets/icons/interface/DarkTheme.tsx
  src/renderer/assets/icons/interface/Debugger.tsx
  src/renderer/assets/icons/interface/Download.tsx
  src/renderer/assets/icons/interface/Exit.tsx
  src/renderer/assets/icons/interface/LightTheme.tsx
  src/renderer/assets/icons/interface/Minus.tsx
  src/renderer/assets/icons/interface/Play.tsx
  src/renderer/assets/icons/interface/Search.tsx
  src/renderer/assets/icons/interface/TableIcon.tsx
  src/renderer/assets/icons/interface/Transfer.tsx
  src/renderer/assets/icons/interface/ZoomInOut.tsx
  src/renderer/data/constants/icon-styles.ts
  src/renderer/features/screens/workspace/components/activitybar/components/button.tsx
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/index.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-root.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-section.tsx
  src/renderer/features/titlebar/menu/menu-bar.tsx
Labels: enhancement

#62 Fix - Refactor menubar
  src/main/menu.ts
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/components/rowDropdown.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/elements/rows.tsx
  src/renderer/features/titlebar/menu-bar.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-root.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-section.tsx
  src/renderer/features/titlebar/menu/flyout/index.ts
  src/renderer/features/titlebar/menu/menu-bar.tsx
  src/renderer/features/titlebar/menu/menu-button.tsx
  src/renderer/features/titlebar/titlebar-left-content.tsx
Labels: bug, enhancement

#63 Fix - Repair visual issues
  src/renderer/features/editors/textual/config/themes/open-plc/openplc.ts
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/elements/header.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/tabs/index.tsx
  tailwind.config.ts
Labels: bug, enhancement

#66 Fix/WIP - Refactor variable table view
  src/renderer/assets/icons/interface/CodeIcon.tsx
  src/renderer/assets/icons/interface/TableIcon.tsx
  src/renderer/features/screens/workspace/components/main-content/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/components/rowDropdown.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/elements/header.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/elements/rows.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/table/index.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel/variable-table/variableCode/index.tsx
  src/renderer/features/variables/data-display/code.tsx
  src/renderer/features/variables/data-display/index.ts
  src/renderer/features/variables/data-display/table.tsx
  src/renderer/features/variables/data/index.ts
  src/renderer/features/variables/index.tsx
  src/renderer/features/variables/types.ts
Labels: bug

#67 Fix - Refactor folder structure
  src/renderer/components/_atoms/button/index.tsx
  src/renderer/components/_atoms/card/index.tsx
  src/renderer/components/_atoms/file/index.tsx
  src/renderer/components/_atoms/index.ts
  src/renderer/components/_atoms/input/index.tsx
  src/renderer/components/_features/[start]/menu/index.tsx
  src/renderer/components/_molecules/search/index.tsx
  src/renderer/components/_organisms/panel/index.tsx
  src/renderer/components/_organisms/titlebar/index.tsx
  src/renderer/components/_templates/[start]/index.ts
  src/renderer/components/_templates/[start]/main-content.tsx
  src/renderer/components/_templates/[start]/side-content.tsx
  src/renderer/components/_templates/[workspace]/index.ts
  src/renderer/components/_templates/[workspace]/main-content.tsx
  src/renderer/components/_templates/[workspace]/side-content.tsx
  src/renderer/components/_templates/app-layout.tsx
  src/renderer/components/_templates/index.ts
  src/renderer/components/elements/card/card-root.tsx
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/features/screens/workspace/components/main-content/index.tsx
Labels: enhancement

#70 Feat - Add create pou to global store
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/main/services/project-service/data/project-data.ts
  src/main/services/project-service/index.ts
  src/renderer/assets/icons/index.ts
  src/renderer/assets/icons/interface/Close.tsx
  src/renderer/components/_atoms/index.ts
  src/renderer/components/_atoms/tab-list/index.tsx
  src/renderer/components/_atoms/tab/index.tsx
  src/renderer/components/_atoms/tree-item/index.tsx
  src/renderer/components/_atoms/tree-view/index.tsx
  src/renderer/components/_features/[workspace]/editor/index.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/index.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/languages/_.register.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/languages/il/il.register.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/languages/il/il.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/themes/_.register.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/themes/openplc/openplc.register.ts
  src/renderer/components/_features/[workspace]/editor/monaco/configs/themes/openplc/openplc.ts
  src/renderer/components/_features/[workspace]/editor/monaco/index.tsx
  src/renderer/components/_molecules/breadcrumbs/index.tsx
  src/renderer/components/_molecules/tabs/index.tsx
  src/renderer/components/_organisms/navigation/index.tsx
  src/renderer/components/_organisms/project-tree/index.tsx
  src/renderer/features/editors/textual/index.tsx
  src/renderer/features/layout.tsx
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/components/main-content/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/tabs/index.tsx
  src/renderer/features/screens/workspace/index.tsx
  src/renderer/features/titlebar/menu-bar.tsx
  src/renderer/providers/router-provider.tsx
  src/renderer/screens/index.ts
  src/renderer/screens/start-screen.tsx
  src/renderer/screens/workspace-screen.tsx
  src/renderer/store/index.ts
  src/renderer/store/slices/editor-slice.ts
  src/renderer/store/slices/index.ts
  src/renderer/store/slices/pous-slice.ts
  src/renderer/store/slices/tabs-slice.ts
  src/renderer/store/slices/workspace-slice.ts
  src/types/transfer.ts
  tsconfig.json
Labels: enhancement
