Repository Autonomy-Logic/openplc-editor, pull requests merged in 2024-04, with the labels that each got.

#71 Fix #69 - Refactor splash screen
  src/main/main.ts
  src/main/modules/preload/scripts/loading/index.ts
  src/main/modules/preload/scripts/loading/splash.html
Labels: bug, enhancement

#72 Feat - create explorer component
  bun.lockb
  package.json
  src/main/main.ts
  src/main/modules/ipc/main.ts
  src/main/services/project-service/data/project-data.ts
  src/renderer/assets/icons/interface/Debugger.tsx
  src/renderer/assets/icons/oplc.tsx
  src/renderer/components/_features/[workspace]/editor/monaco/index.tsx
  src/renderer/components/_molecules/index.ts
  src/renderer/components/_molecules/project-tree/index.tsx
  src/renderer/components/_molecules/tabs/index.tsx
  src/renderer/components/_organisms/explorer/index.tsx
  src/renderer/components/_organisms/explorer/info.tsx
  src/renderer/components/_organisms/explorer/library.tsx
  src/renderer/components/_organisms/explorer/project.tsx
  src/renderer/features/layout.tsx
  src/renderer/features/screens/workspace/components/main-content/index.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/project-tree.tsx
  src/renderer/features/titlebar/menu-bar.tsx
  src/renderer/providers/router-provider.tsx
  src/renderer/screens/test.tsx
  src/renderer/screens/workspace-screen.tsx
  src/renderer/store/slices/platform-slice.ts
  src/renderer/store/slices/tabs-slice.ts
  src/renderer/store/slices/workspace-slice.ts
  src/types/PLC/index.ts
  src/types/PLC/project.ts
  src/types/PLC/units/dataType.ts
  src/types/PLC/units/function.ts
  src/types/PLC/units/functionBlock.ts
  src/types/PLC/units/program.ts
  src/types/PLC/units/variable.ts
  tailwind.config.ts
Labels: enhancement

#73 Feat - Create add pou functionality
  package-lock.json
  package.json
  src/renderer/assets/icons/interface/Arrow.tsx
  src/renderer/assets/icons/project/CExt.tsx
  src/renderer/assets/icons/project/DataType.tsx
  src/renderer/assets/icons/project/Device.tsx
  src/renderer/assets/icons/project/FBD.tsx
  src/renderer/assets/icons/project/Function.tsx
  src/renderer/assets/icons/project/FunctionBlock.tsx
  src/renderer/assets/icons/project/IL.tsx
  src/renderer/assets/icons/project/LD.tsx
  src/renderer/assets/icons/project/PLC.tsx
  src/renderer/assets/icons/project/Program.tsx
  src/renderer/assets/icons/project/Resource.tsx
  src/renderer/assets/icons/project/SFC.tsx
  src/renderer/assets/icons/project/ST.tsx
  src/renderer/components/_atoms/index.ts
  src/renderer/components/_atoms/select/index.tsx
  src/renderer/components/_molecules/index.ts
  src/renderer/components/_molecules/popover/index.tsx
  src/renderer/components/_molecules/pou-card/index.tsx
  src/renderer/components/_organisms/explorer/project.tsx
  src/renderer/features/screens/workspace/components/main-content/index.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/project-tree.tsx
  src/renderer/features/titlebar/menu-bar.tsx
  src/renderer/providers/router-provider.tsx
  src/renderer/screens/workspace-screen.tsx
  tailwind.config.ts
Labels: enhancement

#76 Refactor - Update the tabs slice store
  src/renderer/components/_features/[workspace]/create-pou/card.tsx
  src/renderer/components/_molecules/project-tree/index.tsx
  src/renderer/components/_molecules/tabs/index.tsx
  src/renderer/components/_organisms/explorer/project.tsx
  src/renderer/store/slices/tabs-slice.ts
Labels: bug

#77 Fix - Titlebar menu
  src/main/contracts/types/modules/ipc/main.ts
  src/main/menu.ts
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/renderer/assets/icons/interface/Recent.tsx
  src/renderer/components/_templates/app-layout.tsx
  src/renderer/features/titlebar/menu-bar.tsx
Labels: bug, enhancement
