Repository Autonomy-Logic/openplc-editor, pull requests merged in 2024-02, with the labels that each got.

#37 Fix #12 - Fix start screen proportions
  package-lock.json
  package.json
  src/renderer/components/elements/card/__snapshots__/card.spec.tsx.snap
  src/renderer/components/elements/card/card-root.tsx
  src/renderer/components/elements/card/card.spec.tsx
  src/renderer/components/elements/dropdown/__snapshots__/dropdown.spec.tsx.snap
  src/renderer/components/elements/dropdown/dropdown.spec.tsx
  src/renderer/components/elements/file/file-root.tsx
  src/renderer/components/elements/file/file.spec.tsx
  src/renderer/components/text-editor/config/languages/il/il.spec.ts
  src/renderer/components/text-editor/config/themes/open-plc/open-plc.spec.ts
  src/renderer/components/ui/menu/__snapshots__/menu.spec.tsx.snap
  src/renderer/components/ui/menu/menu.spec.tsx
  src/renderer/features/screens/editor/editor.spec.tsx
  src/renderer/features/screens/editor/index.tsx
  src/renderer/features/screens/start/components/actions-bar/elements/search/search.spec.tsx
  src/renderer/features/screens/start/components/actions-bar/index.tsx
  src/renderer/features/screens/start/components/container/container.spec.tsx
  src/renderer/features/screens/start/components/container/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/carousel-container.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/carousel/carousel.spec.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/header/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/elements/wrapper/index.tsx
  src/renderer/features/screens/start/components/display-example-projects/example-projects.spec.tsx
  src/renderer/features/screens/start/components/display-example-projects/index.tsx
  src/renderer/features/screens/start/components/display-recent-projects/display-recent-project.spec.tsx
  src/renderer/features/screens/start/components/display-recent-projects/elements/display-recent-elements.spec.tsx
  src/renderer/features/screens/start/components/display-recent-projects/elements/wrapper/index.tsx
  src/renderer/features/screens/start/components/display-recent-projects/index.tsx
  src/renderer/features/screens/start/index.tsx
  src/renderer/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: bug, enhancement

#39 Hotfix - Fix spacing of menu
  src/renderer/features/screens/start/components/display-recent-projects/elements/wrapper/index.tsx
  src/renderer/features/screens/start/index.tsx
Labels: bug

#41 Fix #16 - Update preload screen
  src/main/main.ts
  src/main/modules/preload/index.ts
  src/main/modules/preload/scripts/loading/assets/logo.svg
  src/main/modules/preload/scripts/loading/index.ts
  src/main/modules/preload/scripts/loading/splash.html
Labels: bug, enhancement

#44 Feat: Create a wrapper element to the sidebar component
  package-lock.json
  package.json
  src/renderer/features/screens/workspace/components/index.ts
  src/renderer/features/screens/workspace/components/sidebar/index.ts
  src/renderer/features/screens/workspace/components/sidebar/wrapper.tsx
  src/renderer/features/screens/workspace/editor.spec.tsx
  src/renderer/features/screens/workspace/index.tsx
  src/renderer/features/screens/workspace/workspace.spec.tsx
Labels: enhancement

#45 Feat #42 - Create the container wrapper
  package-lock.json
  src/renderer/features/screens/workspace/components/workspace-container.tsx
  src/renderer/features/screens/workspace/index.tsx
Labels: enhancement

#46 Feat #43 - Create workspace sidebar project tree
  .vscode/settings.json
  package-lock.json
  package.json
  src/renderer/assets/icons/outline/index.ts
  src/renderer/assets/icons/solid/interface/folder.tsx
  src/renderer/assets/icons/solid/interface/index.ts
  src/renderer/features/screens/workspace/assets/icons/Fallback.tsx
  src/renderer/features/screens/workspace/assets/icons/index.ts
  src/renderer/features/screens/workspace/assets/icons/interface/Arrow.tsx
  src/renderer/features/screens/workspace/assets/icons/interface/Folder.tsx
  src/renderer/features/screens/workspace/assets/icons/library/CExt.tsx
  src/renderer/features/screens/workspace/assets/icons/library/DataType.tsx
  src/renderer/features/screens/workspace/assets/icons/library/Device.tsx
  src/renderer/features/screens/workspace/assets/icons/library/FBD.tsx
  src/renderer/features/screens/workspace/assets/icons/library/Function.tsx
  src/renderer/features/screens/workspace/assets/icons/library/FunctionBlock.tsx
  src/renderer/features/screens/workspace/assets/icons/library/IL.tsx
  src/renderer/features/screens/workspace/assets/icons/library/LD.tsx
  src/renderer/features/screens/workspace/assets/icons/library/OpenFolder.tsx
  src/renderer/features/screens/workspace/assets/icons/library/PLC.tsx
  src/renderer/features/screens/workspace/assets/icons/library/Program.tsx
  src/renderer/features/screens/workspace/assets/icons/library/Resource.tsx
  src/renderer/features/screens/workspace/assets/icons/library/SFC.tsx
  src/renderer/features/screens/workspace/assets/icons/library/ST.tsx
  src/renderer/features/screens/workspace/assets/index.ts
  src/renderer/features/screens/workspace/components/container/index.tsx
  src/renderer/features/screens/workspace/components/index.ts
  src/renderer/features/screens/workspace/components/panels/bottom-panel.tsx
  src/renderer/features/screens/workspace/components/panels/editor-panel.tsx
  src/renderer/features/screens/workspace/components/panels/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel.tsx
  src/renderer/features/screens/workspace/components/panels/project-tree/header.tsx
  src/renderer/features/screens/workspace/components/panels/project-tree/index.tsx
  src/renderer/features/screens/workspace/components/panels/project-tree/tree.tsx
  src/renderer/features/screens/workspace/components/panels/project-tree/wrapper.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel.tsx
  src/renderer/features/screens/workspace/components/sidebar/index.ts
  src/renderer/features/screens/workspace/components/sidebar/wrapper.tsx
  src/renderer/features/screens/workspace/components/workspace-container.tsx
  src/renderer/features/screens/workspace/index.tsx
  src/renderer/features/screens/workspace/workspace.spec.tsx
Labels: enhancement

#48 Feat #43 - Create workspace sidebar library
  src/renderer/assets/icons/Fallback.tsx
  src/renderer/assets/icons/arrowTransfer.svg
  src/renderer/assets/icons/fileAndFolder.svg
  src/renderer/assets/icons/index.ts
  src/renderer/assets/icons/interface/Arrow.tsx
  src/renderer/assets/icons/interface/Book.tsx
  src/renderer/assets/icons/interface/Folder.tsx
  src/renderer/assets/icons/interface/Magnifier.tsx
  src/renderer/assets/icons/interface/Plus.tsx
  src/renderer/assets/icons/interface/StickArrow.tsx
  src/renderer/assets/icons/interface/Video.tsx
  src/renderer/assets/icons/left-arrow-muted.svg
  src/renderer/assets/icons/library/CloseFolder.tsx
  src/renderer/assets/icons/library/File.tsx
  src/renderer/assets/icons/library/OpenFolder.tsx
  src/renderer/assets/icons/open.svg
  src/renderer/assets/icons/outline/index.ts
  src/renderer/assets/icons/plus.svg
  src/renderer/assets/icons/project/CExt.tsx
  src/renderer/assets/icons/project/DataType.tsx
  src/renderer/assets/icons/project/Device.tsx
  src/renderer/assets/icons/project/FBD.tsx
  src/renderer/assets/icons/project/Function.tsx
  src/renderer/assets/icons/project/FunctionBlock.tsx
  src/renderer/assets/icons/project/IL.tsx
  src/renderer/assets/icons/project/LD.tsx
  src/renderer/assets/icons/project/PLC.tsx
  src/renderer/assets/icons/project/Program.tsx
  src/renderer/assets/icons/project/Resource.tsx
  src/renderer/assets/icons/project/SFC.tsx
  src/renderer/assets/icons/project/ST.tsx
  src/renderer/assets/icons/quitArrow.svg
  src/renderer/assets/icons/recent.svg
  src/renderer/assets/icons/right-arrow.svg
  src/renderer/assets/icons/search.svg
  src/renderer/assets/icons/solid/interface/index.ts
  src/renderer/assets/icons/startSearch.svg
  src/renderer/assets/icons/tutorials.svg
  src/renderer/assets/icons/zoomInOut.svg
  src/renderer/assets/images/darkTheme.png
  src/renderer/assets/images/lightTheme.png
  src/renderer/assets/index.ts
  src/renderer/assets/index.tsx
  src/renderer/components/elements/dropdown/select.tsx
  src/renderer/components/ui/menu/menu-button.tsx
  src/renderer/features/screens/start/components/actions-bar/index.tsx
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/assets/icons/index.ts
  src/renderer/features/screens/workspace/components/panels/project-tree/header.tsx
  src/renderer/features/screens/workspace/components/panels/project-tree/wrapper.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/components/header.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/components/index.ts
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/components/tree-view.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/library-tree.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/project-tree.tsx
Labels: enhancement

#50 Feat #49 - Create workspace navigation tabs
  package-lock.json
  package.json
  src/renderer/features/screens/workspace/components/panels/navigation-panel.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/breadcrumbs/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/tabs/index.tsx
Labels: enhancement

#51 Fix #47 - Refactor workspace activity bar
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/renderer/assets/icons/index.ts
  src/renderer/assets/icons/interface/DarkTheme.tsx
  src/renderer/assets/icons/interface/Download.tsx
  src/renderer/assets/icons/interface/Exit.tsx
  src/renderer/assets/icons/interface/LightTheme.tsx
  src/renderer/assets/icons/interface/Play.tsx
  src/renderer/assets/icons/interface/Search.tsx
  src/renderer/assets/icons/interface/Transfer.tsx
  src/renderer/assets/icons/interface/ZoomInOut.tsx
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/features/screens/workspace/components/container/index.tsx
  src/renderer/features/screens/workspace/components/panels/index.tsx
  src/renderer/features/screens/workspace/index.tsx
  src/renderer/index.ejs
  src/renderer/styles/globals.css
  src/renderer/styles/titlebar.css
  tailwind.config.ts
Labels: bug, enhancement

#52 Feat #49 - Create workspace navigation breadcrumbs
  src/renderer/App.tsx
  src/renderer/assets/icons/library/File.tsx
  src/renderer/data/constants/icon-styles.ts
  src/renderer/data/constants/language-icons.ts
  src/renderer/data/constants/pou-icons.ts
  src/renderer/data/index.ts
  src/renderer/features/screens/workspace/components/panels/navigation-panel/breadcrumbs/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/navigation-panel/tabs/index.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/components/tree-view.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/index.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/info-panel.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/library-tree.tsx
  src/renderer/features/screens/workspace/components/panels/sidebar-panel/project-tree.tsx
  src/renderer/styles/react-resizable.css
Labels: enhancement

#53 Fix - Fix the route handler flow
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/components/activitybar/components/button.tsx
  src/renderer/features/screens/workspace/components/activitybar/components/index.ts
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/providers/router-provider.tsx
Labels: bug, enhancement

#56 Feat #55 - Create menu bar component
  package-lock.json
  package.json
  src/locales/en/menu.json
  src/main/main.ts
  src/main/menu.ts
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/main/modules/preload/index.ts
  src/main/modules/preload/scripts/titlebar/assets/base64Icons/darkThemeIcon.ts
  src/main/modules/preload/scripts/titlebar/assets/base64Icons/index.ts
  src/main/modules/preload/scripts/titlebar/assets/base64Icons/lightThemeIcon.ts
  src/main/modules/preload/scripts/titlebar/assets/base64Icons/logoIcon.ts
  src/main/modules/preload/scripts/titlebar/index.ts
  src/renderer/App.tsx
  src/renderer/assets/icons/oplc.tsx
  src/renderer/features/layout.tsx
  src/renderer/features/screens/start/components/container/container.spec.tsx
  src/renderer/features/screens/start/components/container/index.tsx
  src/renderer/features/screens/start/components/index.ts
  src/renderer/features/screens/start/index.tsx
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/features/screens/workspace/components/container/index.tsx
  src/renderer/features/screens/workspace/components/index.ts
  src/renderer/features/screens/workspace/components/panels/index.tsx
  src/renderer/features/screens/workspace/index.tsx
  src/renderer/features/titlebar/index.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-root.tsx
  src/renderer/features/titlebar/menu/flyout/flyout-section.tsx
  src/renderer/features/titlebar/menu/flyout/index.ts
  src/renderer/features/titlebar/menu/menu-bar.tsx
  src/renderer/features/titlebar/menu/menu-button.tsx
  src/renderer/features/titlebar/titlebar-center-content.tsx
  src/renderer/features/titlebar/titlebar-left-content.tsx
  src/renderer/features/titlebar/titlebar-right-content/index.tsx
  src/renderer/features/titlebar/titlebar-right-content/window-controls-icons.tsx
  src/renderer/index.ejs
  src/renderer/providers/router-provider.tsx
  src/renderer/store/index.ts
  src/renderer/store/slices/platform-slice.ts
  src/renderer/styles/globals.css
  src/renderer/styles/titlebar.css
Labels: bug, enhancement
