Repository Autonomy-Logic/openplc-editor, pull requests merged in 2024-11, with the labels that each got.

#167 Feat - Develop the flow to create a project
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/main/services/project-service/utils/create-project-file.ts
  src/main/services/project-service/utils/index.ts
  src/main/services/project-service/utils/path-picker.ts
  src/renderer/components/_features/[start]/new-project/project-modal.tsx
  src/renderer/components/_features/[start]/new-project/steps/first-step.tsx
  src/renderer/components/_features/[start]/new-project/steps/second-step.tsx
  src/renderer/components/_features/[start]/new-project/steps/third-step.tsx
  src/renderer/components/_features/[start]/new-project/store/index.ts
  src/renderer/components/_templates/[workspace]/main-content.tsx
  src/renderer/features/screens/workspace/components/activitybar/index.tsx
  src/renderer/screens/start-screen.tsx
  src/types/PLC/open-plc.ts
Labels: enhancement

#169 Feat - Create search function
  package-lock.json
  package.json
  src/renderer/components/_atoms/accordion/index.tsx
  src/renderer/components/_features/[workspace]/editor/search-in-project/index.tsx
  src/renderer/components/_features/[workspace]/search/display/tree-view.tsx
  src/renderer/components/_features/[workspace]/search/index.tsx
  src/renderer/components/_molecules/workspace-activity-bar/default/search.tsx
  src/renderer/screens/workspace-screen.tsx
  src/renderer/store/index.ts
  src/renderer/store/slices/index.ts
  src/renderer/store/slices/search/index.ts
  src/renderer/store/slices/search/slice.ts
  src/renderer/store/slices/search/type.ts
  tailwind.config.ts
Labels: enhancement

#168 Feat: Develop the functionality that instantiates a library block
  src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/coil.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/contact.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/mock-node.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/parallel.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/placeholder.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/power-rail.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/index.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/types.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/utilts.ts
  src/renderer/components/_features/[workspace]/create-element/element-card/index.tsx
  src/renderer/components/_features/[workspace]/create-pou/card.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/elements/block/index.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/elements/block/library.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/elements/coil/index.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/elements/contact/index.tsx
  src/renderer/components/_molecules/global-variables-table/selectable-cell.tsx
  src/renderer/components/_molecules/menu-bar/menus/file.tsx
  src/renderer/components/_molecules/menu-bar/menus/recent.tsx
  src/renderer/components/_molecules/rung/body.tsx
  src/renderer/components/_molecules/rung/ladder-utils/elements.ts
  src/renderer/components/_molecules/variables-table/selectable-cell.tsx
  src/renderer/components/_organisms/display-recent-projects/index.tsx
  src/renderer/components/_organisms/explorer/index.tsx
  src/renderer/components/_organisms/explorer/project.tsx
  src/renderer/components/_organisms/variables-editor/index.tsx
  src/renderer/store/slices/flow/slice.ts
  src/renderer/store/slices/flow/types.ts
  src/renderer/store/slices/project/slice.ts
  src/renderer/store/slices/project/types.ts
  src/renderer/store/slices/project/utils/variables.ts
  src/types/PLC/open-plc.ts
  src/types/PLC/units/variable.ts
  src/types/PLC/xml-data/variable/variable-diagram.ts
  src/utils/PLC/language/ladder-xml.ts
  src/utils/PLC/pou-xml.ts
Labels: enhancement

#170 Marcosgabriel/lec 157 - Refactor menu implementation
  src/locales/en/menu.json
  src/main/menu.ts
  src/main/modules/ipc/main.ts
  src/main/modules/ipc/renderer.ts
  src/renderer/assets/icons/about/logo.svg
  src/renderer/components/_molecules/menu-bar/menus/display.tsx
  src/renderer/components/_molecules/menu-bar/menus/edit.tsx
  src/renderer/components/_molecules/menu-bar/menus/file.tsx
  src/renderer/components/_molecules/menu-bar/menus/help.tsx
  src/renderer/components/_molecules/menu-bar/menus/recent.tsx
  src/renderer/components/_molecules/tabs/index.tsx
  src/renderer/components/_molecules/workspace-activity-bar/default/search.tsx
  src/renderer/components/_organisms/about-modal/index.tsx
  src/renderer/components/_organisms/explorer/project.tsx
  src/renderer/components/_organisms/variables-editor/index.tsx
  src/renderer/hooks/index.ts
  src/renderer/hooks/use-remove-tab.tsx
  src/renderer/screens/start-screen.tsx
  src/renderer/screens/workspace-screen.tsx
  src/renderer/store/slices/search/slice.ts
  src/renderer/store/slices/search/type.ts
  src/renderer/store/slices/workspace/slice.ts
  src/renderer/store/slices/workspace/types.ts
Labels: bug, enhancement

#171 LEC-163: Add variables to the ladder blocks
  src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/coil.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/contact.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/index.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/mock-node.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/parallel.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/placeholder.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/power-rail.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/index.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/types.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/utils/utils.ts
  src/renderer/components/_atoms/react-flow/custom-nodes/variable.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/elements/block/index.tsx
  src/renderer/components/_features/[workspace]/editor/graphical/ladder/index.tsx
  src/renderer/components/_molecules/rung/body.tsx
  src/renderer/components/_molecules/rung/ladder-utils/elements.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/diagram/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/drag-n-drop/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/parallel/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/placeholder/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/serial/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/utils/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elements/variable-block/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elementsOld/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elementsOld/parallel/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elementsOld/serial/index.ts
  src/renderer/components/_molecules/rung/ladder-utils/elementsOld/utils/index.ts
  src/renderer/store/slices/flow/slice.ts
  src/renderer/store/slices/flow/types.ts
  src/renderer/store/slices/project/slice.ts
  src/types/PLC/xml-data/pous/languages/ladder-diagram.ts
  src/utils/PLC/language/ladder-xml.ts
Labels: enhancement

#174 Marcosgabriel/lec 122 - Develop the enumerated type editor
  src/renderer/components/_features/[workspace]/create-element/element-card/index.tsx
  src/renderer/components/_features/[workspace]/editor/data-type/index.tsx
  src/renderer/components/_molecules/data-types/array/table/index.tsx
  src/renderer/components/_molecules/data-types/enumerated/index.tsx
  src/renderer/components/_molecules/data-types/enumerated/initial-value.tsx
  src/renderer/components/_molecules/data-types/enumerated/table/editable-cell.tsx
  src/renderer/components/_molecules/data-types/enumerated/table/index.tsx
  src/renderer/components/_organisms/console/index.tsx
  src/renderer/screens/workspace-screen.tsx
  src/renderer/store/slices/project/utils/variables.ts
  src/renderer/store/slices/shared/index.ts
  src/types/PLC/open-plc.ts
Labels: bug, enhancement

#177 LEC-163: Hotfix fixing bugs
  src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
  src/renderer/components/_atoms/react-flow/custom-nodes/variable.tsx
  src/utils/PLC/language/ladder-xml.ts
Labels: bug

#175 LEC-164: Integrate the created user libraries
  src/renderer/components/_atoms/react-flow/custom-nodes/block.tsx
  src/renderer/components/_features/[workspace]/create-pou/card.tsx
  src/renderer/components/_molecules/menu-bar/menus/recent.tsx
  src/renderer/components/_molecules/rung/body.tsx
  src/renderer/components/_organisms/display-recent-projects/index.tsx
  src/renderer/components/_organisms/explorer/index.tsx
  src/renderer/components/_organisms/explorer/library.tsx
  src/renderer/components/_organisms/workspace-activity-bar/index.tsx
  src/renderer/screens/start-screen.tsx
  src/renderer/store/index.ts
  src/renderer/store/slices/flow/types.ts
  src/renderer/store/slices/library/slice.ts
  src/renderer/store/slices/library/type.ts
  src/renderer/store/slices/project/types.ts
  src/renderer/store/slices/search/type.ts
  src/renderer/store/slices/shared/index.ts
  src/renderer/store/slices/workspace/slice.ts
  src/renderer/store/slices/workspace/types.ts
  src/types/PLC/open-plc.ts
Labels: enhancement
